[Client]
	addr = "101.132.38.180:3306"
	dsn = "root:Hive13882!@tcp(101.132.38.180:3306)/hive-dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["root:Hive13882!@tcp(101.132.38.180:3306)/hive-dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8","root:Hive13882!@tcp(101.132.38.180:3306)/hive-dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
